# Generated by Django 5.1.7 on 2025-03-24 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('data_hora', models.DateTimeField()),
                ('local', models.CharField(blank=True, max_length=255)),
                ('categoria', models.CharField(blank=True, choices=[('MUSICA', 'Música'), ('PALESTRA', 'Palestra'), ('WORKSHOP', 'Workshop'), ('SEMINARIO', 'Seminario')], max_length=10)),
            ],
        ),
    ]
